export const REGISTER_START="REGISTER_START";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const LOGOUT_START="LOGOUT_START";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";

export const SET_USER = "SET_USER";

export const GOOGLE_LOGIN_START="GOOGLE_LOGIN_START";
export const GOOGLE_LOGIN_SUCCESS="GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAIL="GOOGLE_LOGIN_FAIL";

export const FACEBOOK_LOGIN_START="FACEBOOK_LOGIN_START";
export const FACEBOOK_LOGIN_SUCCESS="FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAIL="FACEBOOK_LOGIN_FAIL";

export const CLEAR_ERROR="CLEAR_ERROR";